.TH "FETION" 1 "2010-12-26" "" ""
.SH NAME
fetion \- open source command line fetion protocol client
.SH SYNOPSIS
.B fetion
\-f SOURCE \-p PASSWORD \-t DEST \-d MESSAGE
.br
.B fetion
\-f SOURCE \-p PASSWORD \-m \-d MESSAGE
.br
.SH DESCRIPTION
.PP
fetion is a fetion client for Linux based on GTK+2.0, using Fetion  
Protocol Version 4.
.TP
\fB\-f\fR 
specify which number you will use to send a message
.TP
\fB\-t\fR
specify which number you will send a message to
.TP
\fB\-d\fR
message you will send
.TP
\fB\-m\fR
send a message to myself
.TP
\fB\-p\fR
accound password

.SH AUTHOR
Written by Aron Xu <happyaron.xu@gmail.com>.
.RE
.PP

.SH RESOURCES
fetion home page: http://code.google.com/p/ofetion
.RE
.PP

.SH COPYING
Copyright \(co 2009 Aron Xu.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.PP
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.PP
